### ISSUE TITLE
mailer state requires network state

### ISSUE THREAD

**Issue by mitar** [tozd/salt#3]
Can this somehow be lifted?

```
          ID: exim4
    Function: pkg.installed
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     sls: network
```

So on my virtual machine network stack is controlled by the host, so I cannot really use `network` state. On the other hand, I did create pillars with `network.system.hostname` and `network.system.fqdn` which seem to be ones which are needed by exim configuration. Not sure why state is required though?
