### ISSUE TITLE
docker.containers state should update containers

### ISSUE THREAD

**Issue by mitar** [tozd/salt#7]
If any setting is different (valume, env variable, anything), it should stop, remove, and recreate a container.

It seems that currently you have to manually stop and remove a container, which is a bit opposite to what Salt is about, to declaratively define what a new state should be and Salt getting it to there.

**Comment by kostko** [comment]
This should be supported in the newer Salt docker states, so we would need to use those instead of the old dockerio.

**Comment by mitar** [comment]
Yes, currently it is really painful to deploy Docker using our scripts.

**Comment by lukacu** [comment]
+1

**Comment by mitar** [comment]
We migrated to dockerng and it seems this works now. There should be no change required to pillars, it should just work.

Also, now you can specify custom networks. Example:

```
docker:
  containers:
    dbmysql:
      image: tozd/mysql
      network_mode:
        name: servers.example.com
      volumes:
        /srv/storage/dbmysql:
          bind: /var/lib/mysql
        /srv/log/dbmysql:
          bind: /var/log/mysql
```

An interesting fact is that this will now be available as `dbmysql.servers.example.com` and `dbmysql` inside internal DNS. So it resolves both. And reverse DNS is the long form. So name of the network can contain dots it seems.
