### ISSUE TITLE
Supporting more than one IP on a single interface

### ISSUE THREAD

**Issue by lukacu** [tozd/salt#8]
I know that the pillar scheme already supports this, but I was not able to get it working, the interface should be configured like `eth0`, `eth0:0,`eth0:1`and so on. At the moment adding more than one IP to a single interface results in multiple`eth0` directives which (at least according to my research) is not the right way to do it.

**Comment by mitar** [comment]
This is a working example:

```
network:
  system:
    hostname: foo
    fqdn: foo.example.com
  dns:
    ipv4:
      - 193.2.1.66
      - 193.2.1.72
  interfaces:
    eth0:
      ipv4:
        - type: static
          address: 192.168.0.10
          netmask: 255.255.255.0
          gateway: 192.168.0.1
        - type: static
          address: 192.168.0.10
          netmask: 255.255.255.0
          gateway: 192.168.0.1
```
