### ISSUE TITLE
Docker state should create a user-defined Docker network

### ISSUE THREAD

**Issue by mitar** [tozd/salt#9]
With Docker 1.10 we could just create a user-define Docker network for all Salt-managed Docker containers and then we could use their internal DNS server for resolving: https://docs.docker.com/engine/userguide/networking/configure-dns/

We would not need docker-hosts anymore.

Then default network can be used for manual/custom Docker experimentation on the same machine. But automatically deployed images could have their own network.

(I would not complicate for now with supporting custom networks as part of Salt state. One network is enough for now.)

**Comment by mitar** [comment]
Now you can specify custom networks. Example:

```
docker:
  containers:
    dbmysql:
      image: tozd/mysql
      network_mode:
        name: servers.example.com
      volumes:
        /srv/storage/dbmysql:
          bind: /var/lib/mysql
        /srv/log/dbmysql:
          bind: /var/log/mysql
```

An interesting fact is that this will now be available as `dbmysql.servers.example.com` and `dbmysql` inside internal DNS. So it resolves both. And reverse DNS is the long form. So name of the network can contain dots it seems.

Maybe there should be some way to specify default network for all containers, but this can be another issue.
